#Tomcat
server:
  port: 8080
  connection-timeout: 5000ms
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    min-spare-threads: 20
  servlet:
    context-path: /devTemplate

#Spring
spring:
  profiles:
    # 环境 开发dev、测试test、 生产prod
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    #仅映射static资源文件
    static-path-pattern: /static/**
  resources:
    #不为资源文件建立映射
    add-mappings: false
  thymeleaf:
    cache: false

#mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml