spring:
  thymeleaf:
    cache: false
  datasource:
    name: dreamData
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #空闲连接是否被回收
      test-while-idle: true
      #申请连接时是否检测有效性
      test-on-borrow: false
      #归还连接时是否检测有效性
      test-on-return: false
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 50MB
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
server:
  max-http-header-size: 1048576
  tomcat:
    max-connections: 1500
    max-http-post-size: 1048576
    max-threads: 500
  port: 80

#输出sql日志
#logging:
#  level:
#    com.dreamfty.dream.blog.dao.*: debug
